version: "3.9"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # Expose Traefik Dashboard on 8080
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/erebus/traefik.access.log"
      - "--accesslog.fields.headers.names.Host=keep"
      - "--accesslog.fields.headers.names.User-Agent=keep"

      - "--entrypoints.web.address=:80"
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs/:/var/log/erebus/"

  app:
    build: "./services/app"
    labels:
      - "traefik.enable=true"

      # Target router
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
    environment:
      LOG_DIR: "/var/log/erebus/"
    volumes:
      - "./logs/:/var/log/erebus/"
