version: "3.9"

networks:
  loki:
    internal: true

services:
  traefik:
    extends:
      file: "docker-compose.shared.yml"
      service: "traefik"
    command:
      # Expose Traefik Dashboard on 8080
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/erebus/traefik.access.log"
      - "--accesslog.fields.headers.names.Host=keep"
      - "--accesslog.fields.headers.names.Referer=keep"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--accesslog.format=json"
      - "--log.filePath=/var/log/erebus/traefik.log"
      - "--log.format=json"
      - "--log.level=INFO"

      - "--entrypoints.web.address=:80"

  app:
    extends:
      file: "docker-compose.shared.yml"
      service: "app"
    labels:
      - "traefik.enable=true"

      # Target router
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"

  grafana:
    extends:
      file: "docker-compose.shared.yml"
      service: "grafana"
    labels:
      - "traefik.enable=true"

      # Target router
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=web"

  loki:
    extends:
      file: "docker-compose.shared.yml"
      service: "loki"

  promtail:
    extends:
      file: "docker-compose.shared.yml"
      service: "promtail"

  node-exporter:
    extends:
      file: "docker-compose.shared.yml"
      service: "node-exporter"

  prometheus:
    extends:
      file: "docker-compose.shared.yml"
      service: "prometheus"
