{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\"}[1h])",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1h])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Traefik requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate({filename=\"/var/log/erebus/traefik.access.log\",job=\"erebus\"}[1h])",
     "legendFormat": "Acces logs"
    }
   ]
  },
  {
   "title": "Error messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{job=\"docker\"} | json | stream=\"stderr\" | line_format \"{{.log}}\""
    }
   ]
  },
  { "title": "Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Countries",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/erebus/ips.log\",job=\"erebus\"} | json | line_format \"{{.meta_country}}\""
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (meta_browser) (count_over_time({filename=\"/var/log/erebus/ips.log\",job=\"erebus\"} | json | meta_browser != \"\" [$__range]))",
     "legendFormat": "{{meta_browser}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (meta_os) (count_over_time({filename=\"/var/log/erebus/ips.log\",job=\"erebus\"} | json | meta_os != \"\" [$__range]))",
     "legendFormat": "{{meta_os}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  }
 ]
}