version: "3.9"

x-logging: &logging
  driver: loki
  options:
    loki-url: "$LOKI_URL"
    loki-external-labels: "job=gateway,container_name={{.Name}}"
    loki-pipeline-stages: |
      - multiline:
          firstline: '^[a-zA-Z0-9\[\{\(]'

networks:
  edge:
    external: true

services:
  traefik:
    logging: *logging
    image: "traefik:v2.5"
    command:
      - "--accesslog=true"
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entryPoints.metrics.address=:8082"
      - "--entryPoints.traefik.address=:8081"

      - "--metrics.prometheus.entrypoint=metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addServicesLabels=true"

    # Traefik can run on any node but we prob want it on leader node for efficiency
    deploy:
      placement:
        constraints: [node.role == leader]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edge-router-traefik.entrypoints=web"
      - "traefik.http.routers.edge-router-traefik.rule=Host(`traefik.$DOMAIN`)"
      - "traefik.http.services.edge-router-traefik.loadbalancer.server.port=8081"
    networks:
      - edge
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
