version: "3.9"

x-logging: &logging
  driver: loki
  options:
    loki-url: "$LOKI_URL"
    loki-external-labels: "job=monitoring,container_name={{.Name}}"
    loki-pipeline-stages: |
      - multiline:
          firstline: '^[a-zA-Z0-9\[\{\(]'

configs:
  loki:
    file: ${PWD}/config/loki/loki.yaml
  prometheus:
    file: ${PWD}/config/prometheus/prometheus.yml

networks:
  edge:
    external: true
  monitoring:
    external: true

services:
  grafana:
    logging: *logging
    image: grafana/grafana:latest
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAIN`)"
      - "traefik.http.routers.grafana.entrypoints=web"
    deploy:
      placement:
        constraints: [node.hostname == $SWARM_NODE_NAME_CLOUD]
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,marcusolsson-csv-datasource"
    networks:
      - edge
      - monitoring
    volumes:
      - "$PWD/config/grafana/datasources:/etc/grafana/provisioning/datasources/:ro"
      - "$PWD/config/grafana/dashboards:/etc/grafana/provisioning/dashboards/:ro"
      - "$DATA_STORAGE_PATH/grafana:/var/lib/grafana:rw"

  node-exporter:
    logging: *logging
    image: prom/node-exporter:latest
    deploy:
      mode: "global"
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.systemd"
      - "--collector.processes"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  prometheus:
    logging: *logging
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    networks:
      - edge
      - monitoring
    volumes:
      - "$DATA_STORAGE_PATH/prometheus:/prometheus:rw"
