#!/bin/bash

set -e

ufw default deny incoming
ufw default allow outgoing

# Services
ufw allow 80/tcp
ufw allow 443/tcp

# Docker swarm
ufw allow 2377/tcp # cluster management communications
ufw allow 7946/tcp # communication among nodes
ufw allow 7946/udp # communication among nodes
ufw allow 4789/udp # container ingress network.

# NFS
ufw allow 2049/tcp
