#!/bin/bash
# This is a script for syncing this repo to a SSH host

rsync ${PWD} \
	--archive \
	--exclude '.git' \
	--exclude '/**/node_modules/'  \
	--exclude '.env' \
	--exclude '.data' \
	--exclude 'variables.json' \
	--verbose \
	book@home:~
